// Autogenerated from Pigeon (v1.0.12), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "counter.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}


@interface CounterApiCodecReader : FlutterStandardReader
@end
@implementation CounterApiCodecReader
@end

@interface CounterApiCodecWriter : FlutterStandardWriter
@end
@implementation CounterApiCodecWriter
@end

@interface CounterApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation CounterApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[CounterApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[CounterApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *CounterApiGetCodec() {
  static dispatch_once_t s_pred = 0;
  static FlutterStandardMessageCodec *s_sharedObject = nil;
  dispatch_once(&s_pred, ^{
    CounterApiCodecReaderWriter *readerWriter = [[CounterApiCodecReaderWriter alloc] init];
    s_sharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return s_sharedObject;
}


void CounterApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CounterApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.CounterApi.setCounter"
        binaryMessenger:binaryMessenger
        codec:CounterApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setCounterCounterValue:error:)], @"CounterApi api (%@) doesn't respond to @selector(setCounterCounterValue:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_counterValue = args[0];
        FlutterError *error;
        [api setCounterCounterValue:arg_counterValue error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.CounterApi.getCounter"
        binaryMessenger:binaryMessenger
        codec:CounterApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getCounterWithError:)], @"CounterApi api (%@) doesn't respond to @selector(getCounterWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api getCounterWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
