// Autogenerated from Pigeon (v1.0.12), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by CounterApi.
NSObject<FlutterMessageCodec> *CounterApiGetCodec(void);

@protocol CounterApi
- (void)setCounterCounterValue:(NSNumber *)counterValue error:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSNumber *)getCounterWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void CounterApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<CounterApi> *_Nullable api);

NS_ASSUME_NONNULL_END
